version: "3.3"
services:
  app:
    container_name: miapp
    restart: always
    build: ./app-mongo
    ports:
    - "3000:3000"
    links:
    - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
    - ./data:/data/db
    ports:
    - "27017:27017"
  web:
    container_name: web
    image: nginx
    volumes:
    - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/www:/usr/share/nginx/html
    ports:
    - "80:80"
    links:
    - app
